### PR TITLE
docs: migrate to docus

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Migrate to docus

Resolves #131, #139

### CODE REVIEW

**Comment by Atinux** [comment]
Do you need any help on this @ricardogobbosouza ?

**Comment by ricardogobbosouza** [comment]
@Atinux Sorry for the delay, now it's ready for review

**Comment by ricardogobbosouza** [comment]
I just need a social image `docs/public/social-card.png`

**Comment by Atinux** [comment]
https://volta.s3.fr-par.scw.cloud/social_card_f5427208ac.png

@ricardogobbosouza

**Pull request merged**
